# Generated by Django 3.1.12 on 2021-07-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criptoalert',
            name='current_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='criptoalert',
            name='curreny',
            field=models.CharField(default='IDR', max_length=255),
        ),
    ]
