# Generated by Django 3.1.12 on 2021-07-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_auto_20210703_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criptoalert',
            name='current_price',
            field=models.FloatField(default=0),
        ),
    ]
